#.travis.yml

language: node_js
node_js:
  - "node"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli
  - ng set --global packageManager=yarn

script:
  - yarn run build

cache:
  yarn: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: dist
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
